const AI_ENDPOINT='https://hbsloyazdgpkrdadjpox.supabase.co/functions/v1/characterarc-ai';
const AI_SESSION_KEY='characterarc-openai-session-key';
const AI_MODEL_KEY='characterarc-ai-model';
function aiKey(){return sessionStorage.getItem(AI_SESSION_KEY)||''}
function aiModel(){return localStorage.getItem(AI_MODEL_KEY)||'gpt-5-mini'}
function aiConnected(){return Boolean(aiKey())}
function aiStatusHtml(){return `<div class="ai-status"><span class="ai-dot ${aiConnected()?'on':''}"></span><span>${aiConnected()?'AI connected for this browser session':'AI not connected'}</span></div>`}
function aiSetup(after){modal(`<span class="eyebrow">AI connection</span><h2>Connect OpenAI</h2><p>Your API key is kept only in this browser session. It is sent through the CharacterArc server bridge for each request and is not written into the app or repository.</p><div class="ai-note">OpenAI API usage is billed separately from a ChatGPT subscription. CharacterArc continues working with its local coach when AI is disconnected.</div><form id="aif"><div class="field"><label>OpenAI API key</label><div class="key-row"><input type="password" name="key" autocomplete="off" placeholder="sk-…" required><button type="button" class="btn ghost" id="forget">Forget current key</button></div></div><div class="field"><label>Model</label><select name="model"><option value="gpt-5-mini" ${aiModel()==='gpt-5-mini'?'selected':''}>GPT-5 mini — recommended</option><option value="gpt-5" ${aiModel()==='gpt-5'?'selected':''}>GPT-5 — deeper coaching</option><option value="gpt-5-nano" ${aiModel()==='gpt-5-nano'?'selected':''}>GPT-5 nano — lowest cost</option></select></div>${aiStatusHtml()}<div class="modal-actions"><button type="button" class="btn ghost" data-close>Cancel</button><button class="btn primary">Connect AI</button></div></form>`);let f=document.getElementById('aif');document.getElementById('forget').onclick=()=>{sessionStorage.removeItem(AI_SESSION_KEY);f.elements.key.value='';document.querySelector('.ai-status').outerHTML=aiStatusHtml()};f.onsubmit=z=>{z.preventDefault();let d=Object.fromEntries(new FormData(f));if(String(d.key).trim().length<20){alert('That API key appears incomplete.');return}sessionStorage.setItem(AI_SESSION_KEY,String(d.key).trim());localStorage.setItem(AI_MODEL_KEY,d.model);close();after?.()}}
async function aiAsk(mode,commitment,context,outId){if(!aiConnected())return aiSetup(()=>aiAsk(mode,commitment,context,outId));let o=document.getElementById(outId);if(!o)return;o.classList.remove('hidden');o.innerHTML='<div class="ai-loading"><span class="ai-spinner"></span><span>CharacterArc AI is preparing bounded coaching…</span></div>';try{let r=await fetch(AI_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','x-openai-key':aiKey()},body:JSON.stringify({mode,model:aiModel(),commitment,context})});let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'AI request failed.');o.innerHTML=`<span class="eyebrow">AI coaching</span><div class="draft"><small>${e(d.model||aiModel())}</small><p class="ai-output">${e(d.text)}</p><button type="button" class="text-btn" id="aicopy">Copy coaching →</button></div><div class="ai-meta">AI output is a draft. Review every fact and keep only what is true.</div>`;document.getElementById('aicopy').onclick=async()=>{try{await navigator.clipboard.writeText(d.text);document.getElementById('aicopy').textContent='Copied'}catch{document.getElementById('aicopy').textContent='Select and copy manually'}};coach('ai-'+mode,commitment?.id||'',d.text);save()}catch(err){o.innerHTML=`<div class="ai-error"><strong>AI is unavailable.</strong><p>${e(err.message||String(err))}</p></div><div class="ai-note">The local CharacterArc coach still works. Check the key, API billing, or model access, then try again.</div>`}}
function aiQuick(c,mode){modal(`<span class="eyebrow">CharacterArc AI</span><h2>${e(c.title)}</h2><p>AI will use this commitment's visible fields and history. It will not assign a character or trust verdict.</p>${aiStatusHtml()}<div id="aiq" class="result"></div><div class="modal-actions spread"><button type="button" class="btn ghost" id="aiset">AI settings</button><button type="button" class="btn primary" data-close>Close</button></div>`);document.getElementById('aiset').onclick=()=>aiSetup(()=>aiQuick(c,mode));aiAsk(mode,c,{status:st(c),recentHistory:S.history.filter(h=>h.cid===c.id).slice(0,8)},'aiq')}
function aiHub(){modal(`<span class="eyebrow">CharacterArc AI</span><h2>AI coaching connection</h2><p>Connect a key, choose any commitment, and request one bounded coaching mode.</p>${aiStatusHtml()}<div class="picker">${S.commitments.length?S.commitments.filter(c=>!['closed','repaired'].includes(st(c))).map(c=>`<div class="pick"><span><strong>${e(c.title)}</strong><small>${e(c.promise)}</small></span><select data-ai-mode="${c.id}"><option value="quality">Clarify the Say</option><option value="risk">Surface risk</option><option value="report">Draft report</option><option value="repair">Guide repair</option></select><button class="btn coach" data-ai-go="${c.id}">Ask AI</button></div>`).join(''):'<div class="empty">Make a commitment before requesting contextual coaching.</div>'}</div><div class="modal-actions spread"><button type="button" class="btn ghost" id="aiset">AI settings</button><button type="button" class="btn primary" data-close>Close</button></div>`);document.getElementById('aiset').onclick=()=>aiSetup(aiHub);document.querySelectorAll('[data-ai-go]').forEach(b=>b.onclick=()=>{let c=S.commitments.find(x=>x.id===b.dataset.aiGo),m=document.querySelector(`[data-ai-mode="${b.dataset.aiGo}"]`).value;close();aiQuick(c,m)})}
function addAiHome(){let a=document.querySelector('.hero .actions');if(a&&!document.getElementById('aihome')){let b=document.createElement('button');b.className='btn coach';b.id='aihome';b.textContent=aiConnected()?'Ask AI Coach':'Connect AI Coach';b.onclick=aiHub;a.append(b)}}
const _dashboardAI=dashboard;dashboard=function(){_dashboardAI();addAiHome()};
const _hubAI=hub;hub=function(){_hubAI();let grid=document.querySelector('.coach-grid');if(grid&&!document.getElementById('aihubcard')){let d=document.createElement('div');d.className='coach-card';d.id='aihubcard';d.innerHTML=`<span class="num">05</span><h3>AI Coach</h3><p>Use OpenAI for contextual clarification, risk coaching, reporting, and repair drafts.</p><button class="text-btn" id="launchai">${aiConnected()?'Open AI Coach':'Connect AI'} →</button>`;grid.append(d);document.getElementById('launchai').onclick=aiHub}};
const _renderListAI=renderList;renderList=function(f){_renderListAI(f);document.querySelectorAll('.commit').forEach(card=>{let title=card.querySelector('h3')?.textContent,c=S.commitments.find(x=>x.title===title);if(!c||card.querySelector('[data-ai-card]'))return;let s=st(c),m=s==='did'?'report':(['overdue','repair-open'].includes(s)?'repair':s==='risk'?'risk':'quality'),b=document.createElement('button');b.className='btn coach inline-ai';b.dataset.aiCard=c.id;b.textContent='Ask AI';b.onclick=()=>aiQuick(c,m);card.querySelector('.commit-actions')?.append(b)})};
function addFormAI(mode,c,formId,outId,label){let f=document.getElementById(formId);if(!f)return;let actions=f.querySelector('.modal-actions');if(!actions||actions.querySelector('[data-ai-form]'))return;let b=document.createElement('button');b.type='button';b.className='btn coach';b.dataset.aiForm=mode;b.textContent=label||'Ask AI';b.onclick=()=>aiAsk(mode,{...c,...Object.fromEntries(new FormData(f))},{form:Object.fromEntries(new FormData(f)),status:c&&c.id?st(c):'draft'},outId);actions.prepend(b);if(!document.getElementById(outId)){let o=document.createElement('div');o.id=outId;o.className='result hidden';f.append(o)}}
const _commitModalAI=commitModal;commitModal=function(c=null,auto=false){_commitModalAI(c,auto);addFormAI('quality',c||{},'cf','ai-quality','Ask AI to clarify')};
const _riskAI=risk;risk=function(c){_riskAI(c);addFormAI('risk',c,'rf','ai-risk','Ask AI about risk')};
const _reportAI=report;report=function(c,seed={}){_reportAI(c,seed);addFormAI('report',c,'pf','ai-report','Ask AI to draft')};
const _repairAI=repair;repair=function(c){_repairAI(c);addFormAI('repair',c,'xf','ai-repair','Ask AI to guide repair')};
dashboard();
