const virtues=["Honor","Strength","Courage","Generosity","Patience","Peace"];
const articles=[
 ["I — Story","What story are you living inside?"],["II — Success","Success is alignment, not merely achievement."],["III — Alignment","What we say, do, become, and serve move in the same direction."],["IV — Trust","Trust = Integrity × Accountability. Say → Do → Did → Said."],["V — Respect","Honor the work, the people, and the person you are becoming."],["VI — Service","Service is the mission; virtues are the character required to serve well."],["VII — Character","The formed center that carries power, pressure, responsibility, freedom, conflict, opportunity, and success."],["VIII — Compass","Honor, Strength, Courage, Generosity, Patience, and Peace. Honor is True North."],["IX — Expressions","Stability, Leverage, Sacrifice, Grace, Serenity, and Dignity reveal character in the room."],["X — Practice","SpeakUp, ListenUp, PowerUp, LinkUp, TeamUp, GearUp, StepUp, LevelUp."],["XI — Community","CircleUp is communal rehearsal."],["XII — Personal Formation","CORE Work is personal rehearsal."],["XIII — Christ / The Center","Christ is the center, source, measure, model, invitation, and fulfillment of rightly ordered success."],["XIV — Drift","The answer to drift is return."],
];
const scenarios=[
{title:"The Missed Promise",virtue:"Strength",skills:"SpeakUp + PowerUp",context:"You publicly committed to deliver a report by Friday. On Thursday afternoon, it is clear the work will not be ready.",pressure:"Your credibility, the team's schedule, and your desire to appear dependable are all at stake.",choices:[
 {t:"Work through the night and deliver something—anything—on time.",level:"mixed",score:1,text:"Energy protects the deadline, but force can hide reality and create invisible costs. Strength is reliable, humane follow-through—not heroic concealment.",p:["Trust","Integrity","Respect","Return"]},
 {t:"Say nothing until Friday, then explain why the deadline was unrealistic.",level:"drift",score:0,text:"This breaks both sides of the trust loop: Say did not become Do, and what actually happened was not Said in time for others to respond.",p:["Trust Loop","Accountability","Alignment"]},
 {t:"Tell the truth now, own the miss, present the completed portion, and renegotiate a specific delivery plan.",level:"good",score:3,text:"This protects clarity and restores alignment. Accountability does not erase the miss; it makes repair possible by bringing Did back to Said.",p:["Strength","Say → Do → Did → Said","Dignity","StepUp"]}]},
{title:"The Public Correction",virtue:"Honor",skills:"SpeakUp + ListenUp",context:"A respected colleague shares inaccurate information in a crowded meeting. The error could shape an important decision.",pressure:"Correcting them publicly may embarrass them. Staying quiet may let the team act on false information.",choices:[
 {t:"Correct them sharply so everyone knows the facts.",level:"mixed",score:1,text:"Truth without reverence becomes bluntness. Honor protects both reality and the person carrying it.",p:["Honor","Respect","Clarity"]},
 {t:"Stay silent and message them privately after the decision.",level:"drift",score:0,text:"Politeness without timely truth allows drift. The work and the people affected by the decision also deserve respect.",p:["Alignment","Service","SpeakUp"]},
 {t:"Pause the decision, name the conflicting information without attacking intent, and invite clarification.",level:"good",score:3,text:"Honor tells the truth with reverence. It makes the room clearer while preserving the colleague's dignity and capacity to participate.",p:["Honor","True North","SpeakUp","ListenUp"]}]},
{title:"The Risky Concern",virtue:"Courage",skills:"PowerUp + LinkUp",context:"You notice a pattern that may compromise client care, but the evidence is incomplete and the person responsible has more authority than you.",pressure:"Speaking could strain relationships. Silence could allow harm. Acting alone could overstate what you know.",choices:[
 {t:"Post the concern broadly so no one can suppress it.",level:"drift",score:0,text:"Energy without social wisdom becomes recklessness. Courage is not maximum exposure; it is worthy action shaped by truth, relationship, and responsibility.",p:["Courage","Dignity","Respect"]},
 {t:"Wait until you have perfect proof.",level:"mixed",score:1,text:"Careful inquiry matters, but perfection can become avoidance. Constitutional courage moves proportionately before certainty is complete.",p:["Courage","Explore","Service"]},
 {t:"Document what you know, consult a trustworthy channel, and raise the concern with a clear request for review.",level:"good",score:3,text:"This mobilizes connection in service of what is worthy. It neither acts alone nor hands responsibility away.",p:["Courage","LinkUp","StepUp","Service"]}]},
{title:"The Scarce Opportunity",virtue:"Generosity",skills:"LinkUp + TeamUp",context:"A high-visibility assignment could accelerate your career. A quieter teammate is better positioned to lead it but is often overlooked.",pressure:"You want to grow. The team needs the strongest outcome. The organization has not created fair access to opportunity.",choices:[
 {t:"Take the assignment; you cannot help others if you never advance.",level:"mixed",score:1,text:"Stewarding your own growth is legitimate, but isolated advancement can reinforce a system that withholds opportunity from others.",p:["Generosity","Service","Respect"]},
 {t:"Decline and insist the teammate receive it, regardless of what they want.",level:"mixed",score:1,text:"Giving without listening can become paternalism. Generosity increases agency rather than deciding for another person.",p:["Dignity","ListenUp","Generosity"]},
 {t:"Invite the teammate into an honest conversation and propose a shared or sponsored leadership pathway.",level:"good",score:3,text:"Structured generosity shares credit, access, and responsibility while strengthening the whole. It creates capacity rather than a symbolic gesture.",p:["Generosity","LinkUp","TeamUp","Grace"]}]},
{title:"The Slower Learner",virtue:"Patience",skills:"TeamUp + GearUp",context:"A new teammate is learning a critical process more slowly than expected. Deadlines are tightening and others are becoming frustrated.",pressure:"Moving too slowly may hurt service. Moving without them may protect output while preventing formation.",choices:[
 {t:"Take over the work until the pressure passes.",level:"mixed",score:1,text:"This may protect the immediate result, but repeated rescue can prevent shared competence and quietly create dependency.",p:["Patience","TeamUp","Formation"]},
 {t:"Let them struggle without intervention so they learn faster.",level:"drift",score:0,text:"Abandonment is not patience. Practice must protect dignity and service while creating a real path toward responsibility.",p:["Dignity","Service","Respect"]},
 {t:"Define the non-negotiable outcome, reduce the task into coached repetitions, and set a review point.",level:"good",score:3,text:"Patience is paced collaboration. It moves at the speed of learning without surrendering the responsibility to serve.",p:["Patience","GearUp","TeamUp","LevelUp"]}]},
{title:"The Heated Disagreement",virtue:"Peace",skills:"GearUp + StepUp",context:"Two committed team members disagree about a new approach. The conversation is becoming personal and others are withdrawing.",pressure:"Ending the debate may restore quiet. Letting it continue may surface truth but damage relationship and trust.",choices:[
 {t:"End the conversation and make the decision yourself.",level:"mixed",score:1,text:"Authority can contain harm, but quiet is not automatically peace. Unexamined conflict often returns as drift.",p:["Peace","Authority","Return"]},
 {t:"Let them keep arguing until one position wins.",level:"drift",score:0,text:"Inquiry without regard becomes agitation. Constitutional practice protects people fiercely while ideas are examined vigorously.",p:["Dignity","Respect","Peace"]},
 {t:"Pause, restate the shared mission, separate facts from interpretations, and set a dignified process for testing both claims.",level:"good",score:3,text:"Peace is principled harmony: truth-seeking without violence to people. It makes conflict more truthful and relationship more intact.",p:["Peace","Explore","Respect","Dignity"]}]},
{title:"The Attractive Shortcut",virtue:"Honor",skills:"SpeakUp + StepUp",context:"A shortcut would make your results look better this quarter. It is technically permitted but obscures what clients actually experienced.",pressure:"Leadership expects improvement. The team is tired. The shortcut may buy time without breaking a written rule.",choices:[
 {t:"Use it because the metric is only one imperfect representation anyway.",level:"drift",score:0,text:"Constitutional integrity is more than technical permission. A result that hides reality separates achievement from alignment.",p:["Honor","Integrity","Success"]},
 {t:"Refuse privately but avoid challenging how the metric is used.",level:"mixed",score:1,text:"Personal refusal protects your action, but the system remains vulnerable to the same drift. Honor also serves the shared work.",p:["SpeakUp","Service","Honor"]},
 {t:"Name the distortion, report the honest result, and propose a transparent companion measure.",level:"good",score:3,text:"This keeps truth and service together. Honor asks not merely what is allowed, but what is worthy of the work and the people.",p:["True North","Honor","Alignment","Service"]}]},
{title:"The Exhausted Leader",virtue:"Strength",skills:"PowerUp + SpeakUp",context:"Your team depends on you, but your attention and energy are depleted. You are making preventable mistakes and becoming impatient.",pressure:"Rest feels irresponsible. Continuing at the same pace risks harm to people and work.",choices:[
 {t:"Push harder until the important season ends.",level:"drift",score:0,text:"Force can imitate strength for a time. But strength sustains ethical action; it does not spend the person until integrity becomes impossible.",p:["Strength","Respect","Character"]},
 {t:"Withdraw without explaining because you need to protect yourself.",level:"mixed",score:1,text:"Recovery is necessary, but silent withdrawal breaks coordination and places hidden burdens on others.",p:["Accountability","TeamUp","Respect"]},
 {t:"Tell the truth about capacity, redistribute responsibilities, and establish a recovery-and-return plan.",level:"good",score:3,text:"This aligns communication and energy. It treats limits as information to steward rather than shame to conceal.",p:["Strength","PowerUp","SpeakUp","Return"]}]},
{title:"The Unpopular Decision",virtue:"Courage",skills:"PowerUp + LinkUp",context:"The decision most consistent with the mission will disappoint a vocal group whose support matters.",pressure:"You could preserve approval, preserve the mission, or attempt to hold both without pretending there is no cost.",choices:[
 {t:"Make the mission-aligned decision without explanation; leaders must be decisive.",level:"mixed",score:1,text:"Decision may be necessary, but courage without relational stewardship can isolate authority and weaken trust.",p:["Courage","Communication","Dignity"]},
 {t:"Choose the popular option and revisit the issue later.",level:"drift",score:0,text:"Approval becomes a rival story of success. Drift often begins when immediate comfort outranks what is worthy.",p:["Story","Mission","Drift"]},
 {t:"Make the decision, explain the worthy purpose and real costs, invite response, and remain accountable for impact.",level:"good",score:3,text:"Courage acts despite social risk while drawing people into truthful relationship. It does not confuse consensus with legitimacy.",p:["Courage","Service","Accountability","LinkUp"]}]},
{title:"The Hidden Contributor",virtue:"Generosity",skills:"LinkUp + TeamUp",context:"A successful project is being celebrated. Public credit is flowing mostly to visible leaders, while several contributors remain unnamed.",pressure:"Interrupting the celebration may feel awkward. Saying nothing preserves the moment but distorts the story of how success happened.",choices:[
 {t:"Let it pass; everyone knows teamwork matters.",level:"drift",score:0,text:"Unspoken gratitude cannot correct a public distortion. Generosity makes contribution visible and opportunity more trustworthy.",p:["Generosity","Story","Respect"]},
 {t:"List every contributor immediately, even if you are unsure of their role.",level:"mixed",score:1,text:"The instinct is generous, but imprecision can create a new distortion. Truth and credit belong together.",p:["Honor","Generosity","Clarity"]},
 {t:"Add the missing contributors accurately, name what each made possible, and improve the team's credit practice.",level:"good",score:3,text:"Architected abundance shares credit and changes the system that made contribution invisible.",p:["Generosity","TeamUp","Grace","Service"]}]},
{title:"The Constant New Idea",virtue:"Patience",skills:"TeamUp + GearUp",context:"A creative leader introduces a new direction before the last experiment has been evaluated. The team feels both excited and destabilized.",pressure:"Rejecting the idea may punish creativity. Pursuing it immediately may deepen fatigue and prevent learning.",choices:[
 {t:"Start the new idea while enthusiasm is high.",level:"drift",score:0,text:"Exploration without coordination becomes impulsivity. Newness can become a story that exempts us from finishing and learning.",p:["Patience","Explore","Accountability"]},
 {t:"Ban new ideas until the current plan is complete.",level:"mixed",score:1,text:"Structure protects focus, but rigid closure can turn patience into stagnation. Curiosity still needs a trustworthy container.",p:["Patience","GearUp","Discovery"]},
 {t:"Capture the idea, define the decision clock, finish the current learning cycle, then evaluate with clear criteria.",level:"good",score:3,text:"Patience creates a pace where curiosity can mature into shared wisdom rather than repeated disruption.",p:["Patience","Decision Clock","GearUp","Return"]}]},
{title:"The Quiet Room",virtue:"Peace",skills:"ListenUp + StepUp",context:"A meeting appears calm, but several people who will carry the decision have said almost nothing. You sense disagreement beneath the surface.",pressure:"Inviting dissent may lengthen the meeting and expose conflict. Moving on may preserve efficiency while weakening ownership.",choices:[
 {t:"Accept the silence as consent and proceed.",level:"drift",score:0,text:"Quietism mistakes absence of conflict for peace. Unspoken resistance later becomes division, confusion, or passive noncompliance.",p:["Peace","ListenUp","Trust"]},
 {t:"Call on the quietest person and demand an honest answer.",level:"mixed",score:1,text:"The truth matters, but forced vulnerability can violate dignity. Peace creates conditions for candor rather than extracting it.",p:["Dignity","Respect","SpeakUp"]},
 {t:"Name the silence without accusation, reopen the decision boundary, and offer multiple safe ways to contribute.",level:"good",score:3,text:"This joins inquiry and respect. Peace increases truthfulness while protecting the person and the shared work.",p:["Peace","ListenUp","Dignity","Unity"]}]}
];